### ISSUE TITLE
cherrymusic not starting with python 2.7

### ISSUE THREAD

**Issue by 6arms1leg** [devsnd/cherrymusic#270]
cherrymusic should work with python>=2.6 now, right? the python 2 branch is merged?

i just tested the newest version on the new test server with python 2.7 and i get following error:

```
$ python2.7 ./cherrymusic
Traceback (most recent call last):
  File "./cherrymusic", line 60, in <module>
    import cherrymusicserver
  File "/home/guest/cherrymusic-devel/cherrymusicserver/__init__.py", line 52, in <module>
    cherrypy.process.servers.wait_for_occupied_port = fake_wait_for_occupied_port
AttributeError: 'module' object has no attribute 'process'
```

am i missing something here? (python2.7 + cherrypy are installed)

**EDIT:**
using python3 and locally downloading cherrypy+stagger it works fine.
