### ISSUE TITLE
Failed to load file browser

### ISSUE THREAD

**Issue by tacul** [devsnd/cherrymusic#530]
Hi! I´m gettin the error "Failed to load file browser" after installed the 0.35.0 i already deleted the static media folder and re-running setup.py, but i have still the same issue.

![image](https://cloud.githubusercontent.com/assets/6086049/6940525/3e0eec82-d84e-11e4-99c3-ec6fb9252165.png)

only for info:
the result for cherrymusic --info is:
```
E:\cherryMusic\cherryMusic>python cherrymusic --info
CherryMusic Server 0.34.1

CherryPy: 3.6.0
Python: CPython 3.4.3
Platform: Windows-2008ServerR2-6.1.7601-SP1

configuration dir:

C:\Users\Administrator\AppData\Roaming\cherrymusic* server data dir:
C:\Users\Administrator\AppData\Roaming\cherrymusic* static resources dir:
E:\cherryMusic\cherryMusic* server package dir:
E:\cherryMusic\cherryMusic\cherrymusicserver* process working dir:
E:\cherryMusic\cherryMusic*
locale: (None, None), default: ('es_AR', 'cp1252')
filesystem encoding: mbcs

(Do not parse this output.)

E:\cherryMusic\cherryMusic>
```
Anything i can do to help solving this issue?

Thanks!!

**Comment by devsnd** [comment]
Hi tacul!

Sorry to hear you having problems. Can you please post the output from the server after you tried using the directory listing? There should be the stack trace which can tell us what went wrong.

Thank you!

**Comment by rtaibah** [comment]
Having the same issue. Here is the output from my server:
    [150414-15:15] 176.44.94.63 - - [14/Apr/2015:15:15:04] "POST /api/heartbeat HTTP/1.1" 200 14 "http://volans.whatbox.ca:40491/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:37.0) Gecko/20100101 Firefox/37.0"
    [150414-15:15] 176.44.94.63 - - [14/Apr/2015:15:15:11] "POST /api/heartbeat HTTP/1.1" 200 14 "http://volans.whatbox.ca:40491/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:37.0) Gecko/20100101 Firefox/37.0"

**Comment by devsnd** [comment]
Hi Rami!

Can you please post the log output just after you have clicked the "browse files" button? The output you posted before is just your browser "pinging" the cherrymusic server (instead of /api/heartbeat there should be a /api/listdir call)

thanks!

**Comment by rtaibah** [comment]
Sorry about that. I suspected as much, just not familiar with your logs...

```[150415-08:04] 176.44.94.63 - - [15/Apr/2015:08:04:38] "POST /api/listdir HTTP/1.1" 400 702 "http://***.***.***/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:37.0) Gecko/20100101 Firefox/37.0"```

**Comment by tilboerner** [comment]
Here's a stack trace from @xMinerv in #544:

```
[150415-17:06] ERROR   : [15/Apr/2015:17:06:57] HTTP Traceback (most recent call last):
  File "/home/user/cherrymusic/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/home/user/cherrymusic/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/user/cherrymusic/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/user/cherrymusic/cherrymusicserver/httphandler.py", line 290, in api
    return json.dumps({'data': handler(**handler_args)})
TypeError: api_listdir() missing 1 required positional argument: 'directory'
```
We need to see how well that goes with the `400` status code reported by @rtaibah.

**Comment by devsnd** [comment]
I guess this is a regression from #506. See: https://github.com/devsnd/cherrymusic/commit/4cffd9ad15276f0456341f29a03075c658dc6b2f

But this might as well be a problem with the browser cache, because I thought we had fixed any `api('listdir', ...)` calls to always include the directory.

@tacul and @rtaibah, could you please clear your browser cache to see if the problem persists?

**Comment by tacul** [comment]
Hi @devsnd ! We are currently looking at this issue together (https://github.com/devsnd/cherrymusic/issues/528). I do not want to interfere with the tests. Once resolved, we continue with the problem of file browser if thats OK with you. Thanks again!

**Comment by rtaibah** [comment]
Hi @devsend, all history wiped out from Chrome. Still same problem. My main browser is FF which is also experiencing this.

**Comment by devsnd** [comment]
hey @tacul & @rtaibah,

Sorry for the long wait! I've written a small patch that should take care of the issue. Can you please check out if the devel branch version works now for you?

**Comment by tacul** [comment]
it Works!!! thanks! @devsnd !!!
